### ISSUE TITLE
Docker image for arm/aarch64

### ISSUE THREAD

**Issue by blackVanilla** [AgustinSRG/rtmp-server#5]
Please add docker images for other platforms like arm and aarch64 to docker hub.
Manual docker build worked perfect on aarch64 host.

**Comment by AgustinSRG** [comment]
Hi. Thanks for the suggestion. I never considered building for other architectures, since all my machines are AMD64, but it can be a problem when trying to run the server in ARM machines.

I modified the [GitHub actions workflow](https://github.com/AgustinSRG/rtmp-server/blob/master/.github/workflows/docker-image.yml) to build a multi-platform image and publish it to Docker Hub.

I released a new version (`1.2.2`) and the workflow successfully built and published the image for `linux/amd64`, `linux/arm64` (`aarch64`), `linux/arm/v7` and `linux/arm/v6`: https://hub.docker.com/r/asanrom/rtmp-server/tags

Feel free to open other issues in case you find problems or to make any other suggestions to improve the project.
